### PR TITLE
fix appveyor build

### LINKED ISSUE #9: Windows 7 killing not working
I wrote code to terminate a node process on windows 7 but it says it cannot find 'ps' and then does not work. Is there a work around it?
regards

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #9 
Note: depends on #20 and #23

### CODE REVIEW

File: test/exec/child.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
 // does nothing child process
 console.log("Child process.id: "+process.pid);
 console.log(" - - - - - - - - - - - - - - - - - - - - - - - ");
+// keep process alive for one minute
+setTimeout(function () {}, 60000);
```
Comment (nelsonic) [inline test/exec/child.js:5]: @jedwards1211 please clarify why this timeout is required and why it _has_ to be for 60 sec. thanks!

Comment (jedwards1211) [reply test/exec/child.js:5]: Maybe it's not necessary, I got confused because the windows tests are still very timing-dependent, but I was surprised the tests were ever working because the child processes will exit once they finish those two `console.log`s.  Using `setTimeout` keeps the process alive.  The timeout definitely doesn't have to be for one minute though.  It could just be a bit longer than the duration of the tests.

Comment (jedwards1211) [reply test/exec/child.js:5]: As far as the timing of windows tests, I guess the best thing is to make the first test poll until all the child processes are gone, with a test timeout of 5 seconds or so (sometimes it takes more than 1 second for the child processes to go away).

Comment (nelsonic) [reply test/exec/child.js:5]: agree. poll. 👍

Comment (jedwards1211) [reply test/exec/child.js:5]: do you want to go ahead and merge this, or do you want me to implement polling?
Polling does have one drawback, I realized.  It's unlikely but possible that a new process starts with the same pid as one that was killed, causing terminate to poll forever.
I have implemented polling in [my crater-util package](https://github.com/jedwards1211/crater-util/blob/master/src/kill.js) (ironically I ended up using that instead of this) and it works well enough for my integration tests though.

Comment (nelsonic) [reply test/exec/child.js:5]: Ok. let's merge it and publish a new version. if we get a bug report we can go from there. 👍
